services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.18.3
    volumes:
      - ./internal/db/migrations:/migrations:ro
    command: ["-path=/migrations", "-database", "${DB_URL}", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  shortner:
    build:
      context: .
    environment:
      ENV: docker
    ports:
      - "${HOST_PORT}:${API_PORT}"
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
